[package]
name = "zone-list"
version = "0.1.0"
edition = "2024"

[dependencies]
openapi-rs = { path = "../../../openapi-rs" }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1"
dotenvy = "0.15"
