[workspace]
resolver = "2"
members = []
exclude = []

[package]
name = "openapi-rs"
version = "0.1.0"
edition = "2024"
description = "open api for rust"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1"
dotenvy = "0.15.7"
serde_urlencoded = "0.7"
md-5 = "0.10"
sha1 = "0.10"
hex = "0.4"
